### ISSUE TITLE
反馈两个问题

### ISSUE THREAD

**Issue by WolkeAtreide** [zxhd863943427/siyuan-slide-mode#2]
1.能不能加个背景，白底太亮了。
2.导图显示不了
![image](https://user-images.githubusercontent.com/101959415/236801090-4f379f97-c2b3-4bcb-abc3-4d4478e719ed.png)

**Comment by zxhd863943427** [comment]
1. 背景是可以自定义的。详情见marp文档
2. 导图？这个是支持不了的，只支持GFM语法。
